import '../styles/globals.css'
import 'react-day-picker/dist/style.css';
import Head from 'next/head'
import type { AppProps } from 'next/app'

import Header from '../components/Header'
import Footer from '../components/Footer'

import {
	HomeProvider,
	GeneralProvider
} from '../state-management';

function MyApp({ Component, pageProps }: AppProps) {
	
	return (
		<>
			<Head>
				<title>Find Hotel Clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
				<script src="https://kit.fontawesome.com/165d067c39.js"></script>
			</Head>
			<GeneralProvider>
				<HomeProvider>
					<Header/>
					<Component {...pageProps} />
					<Footer/>
				</HomeProvider>
			</GeneralProvider>
		</>
	)
}

export default MyApp
